//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menees.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Menees.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code contains space characters used for indentation..
        /// </summary>
        internal static string Men001Description {
            get {
                return ResourceManager.GetString("Men001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs should be used for indentation..
        /// </summary>
        internal static string Men001MessageFormat {
            get {
                return ResourceManager.GetString("Men001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs should be used for indentation.
        /// </summary>
        internal static string Men001Title {
            get {
                return ResourceManager.GetString("Men001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines should be a readable, maintainable length..
        /// </summary>
        internal static string Men002Description {
            get {
                return ResourceManager.GetString("Men002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line must be no longer than {0} characters (now {1})..
        /// </summary>
        internal static string Men002MessageFormat {
            get {
                return ResourceManager.GetString("Men002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line is over {0} characters (now {1})..
        /// </summary>
        internal static string Men002MessageFormatNotify {
            get {
                return ResourceManager.GetString("Men002MessageFormatNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line is too long.
        /// </summary>
        internal static string Men002Title {
            get {
                return ResourceManager.GetString("Men002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line is long.
        /// </summary>
        internal static string Men002TitleNotify {
            get {
                return ResourceManager.GetString("Men002TitleNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods should be a readable, maintainable length..
        /// </summary>
        internal static string Men003Description {
            get {
                return ResourceManager.GetString("Men003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be no longer than {1} lines (now {2})..
        /// </summary>
        internal static string Men003MessageFormat {
            get {
                return ResourceManager.GetString("Men003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is too long.
        /// </summary>
        internal static string Men003Title {
            get {
                return ResourceManager.GetString("Men003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property accessors should be a readable, maintainable length..
        /// </summary>
        internal static string Men004Description {
            get {
                return ResourceManager.GetString("Men004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be no longer than {1} lines (now {2})..
        /// </summary>
        internal static string Men004MessageFormat {
            get {
                return ResourceManager.GetString("Men004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property accessor is too long.
        /// </summary>
        internal static string Men004Title {
            get {
                return ResourceManager.GetString("Men004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files should be a readable, maintainable length..
        /// </summary>
        internal static string Men005Description {
            get {
                return ResourceManager.GetString("Men005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} must be no longer than {1} lines (now {2})..
        /// </summary>
        internal static string Men005MessageFormat {
            get {
                return ResourceManager.GetString("Men005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too long.
        /// </summary>
        internal static string Men005Title {
            get {
                return ResourceManager.GetString("Men005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #regions should be used to group related items in large code files..
        /// </summary>
        internal static string Men006Description {
            get {
                return ResourceManager.GetString("Men006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #regions should be used{0}..
        /// </summary>
        internal static string Men006MessageFormat {
            get {
                return ResourceManager.GetString("Men006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #regions should be used.
        /// </summary>
        internal static string Men006Title {
            get {
                return ResourceManager.GetString("Men006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using a single return keeps control flow simple and makes refactoring easier..
        /// </summary>
        internal static string Men007Description {
            get {
                return ResourceManager.GetString("Men007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple return statements ({0}) are used in {1}..
        /// </summary>
        internal static string Men007MessageFormat {
            get {
                return ResourceManager.GetString("Men007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A return statement is used in {0}, which returns void..
        /// </summary>
        internal static string Men007MessageFormatVoid {
            get {
                return ResourceManager.GetString("Men007MessageFormatVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a single return.
        /// </summary>
        internal static string Men007Title {
            get {
                return ResourceManager.GetString("Men007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file&apos;s name should match or include the name of the main type it contains..
        /// </summary>
        internal static string Men008Description {
            get {
                return ResourceManager.GetString("Men008Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name {0} {1}..
        /// </summary>
        internal static string Men008MessageFormat {
            get {
                return ResourceManager.GetString("Men008MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name should match type.
        /// </summary>
        internal static string Men008Title {
            get {
                return ResourceManager.GetString("Men008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using preferred exception types makes calling code more consistent and maintainable..
        /// </summary>
        internal static string Men009Description {
            get {
                return ResourceManager.GetString("Men009Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} instead of {1}..
        /// </summary>
        internal static string Men009MessageFormat {
            get {
                return ResourceManager.GetString("Men009MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the preferred exception type.
        /// </summary>
        internal static string Men009Title {
            get {
                return ResourceManager.GetString("Men009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using named constants instead of numeric literals in expressions improves readability and maintainability..
        /// </summary>
        internal static string Men010Description {
            get {
                return ResourceManager.GetString("Men010Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The numeric literal {0} should be replaced with a named constant..
        /// </summary>
        internal static string Men010MessageFormat {
            get {
                return ResourceManager.GetString("Men010MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid magic numbers.
        /// </summary>
        internal static string Men010Title {
            get {
                return ResourceManager.GetString("Men010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using directives should be indented consistently based on their nesting level inside a namespace..
        /// </summary>
        internal static string Men011Description {
            get {
                return ResourceManager.GetString("Men011Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The using directive should be indented consistent with its nesting level..
        /// </summary>
        internal static string Men011MessageFormat {
            get {
                return ResourceManager.GetString("Men011MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align using directives.
        /// </summary>
        internal static string Men011Title {
            get {
                return ResourceManager.GetString("Men011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags enum members should be powers of two or bitwise-or combinations of named members..
        /// </summary>
        internal static string Men012Description {
            get {
                return ResourceManager.GetString("Men012Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags enum member {0}.{1} has value {2}, which is not a {3}power of two..
        /// </summary>
        internal static string Men012MessageFormat {
            get {
                return ResourceManager.GetString("Men012MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags enum member {0}.{1} should explicitly assign its value to zero or a power of two..
        /// </summary>
        internal static string Men012MessageFormatNoValue {
            get {
                return ResourceManager.GetString("Men012MessageFormatNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags should be powers of two.
        /// </summary>
        internal static string Men012Title {
            get {
                return ResourceManager.GetString("Men012Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC times are safer because they&apos;re unambiguous and always increasing..
        /// </summary>
        internal static string Men013Description {
            get {
                return ResourceManager.GetString("Men013Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} instead of {1}..
        /// </summary>
        internal static string Men013MessageFormat {
            get {
                return ResourceManager.GetString("Men013MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use UTC time.
        /// </summary>
        internal static string Men013Title {
            get {
                return ResourceManager.GetString("Men013Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TryGetValue does a single key lookup, which is more efficient than doing a ContainsKey lookup and a this[key] lookup..
        /// </summary>
        internal static string Men014Description {
            get {
                return ResourceManager.GetString("Men014Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} instead of {1} and {2}..
        /// </summary>
        internal static string Men014MessageFormat {
            get {
                return ResourceManager.GetString("Men014MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer TryGetValue.
        /// </summary>
        internal static string Men014Title {
            get {
                return ResourceManager.GetString("Men014Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred terms and casing should be used in identifiers..
        /// </summary>
        internal static string Men015Description {
            get {
                return ResourceManager.GetString("Men015Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} instead of {1}..
        /// </summary>
        internal static string Men015MessageFormat {
            get {
                return ResourceManager.GetString("Men015MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use preferred terms.
        /// </summary>
        internal static string Men015Title {
            get {
                return ResourceManager.GetString("Men015Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-level statements should be avoided in long-term code for consistency and maintainability with other object-oriented modules..
        /// </summary>
        internal static string Men016Description {
            get {
                return ResourceManager.GetString("Men016Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use object-oriented methods instead of top-level statements..
        /// </summary>
        internal static string Men016MessageFormat {
            get {
                return ResourceManager.GetString("Men016MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid top-level statements.
        /// </summary>
        internal static string Men016Title {
            get {
                return ResourceManager.GetString("Men016Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A private set accessor is not needed when an auto property is only assigned in the constructor..
        /// </summary>
        internal static string Men017Description {
            get {
                return ResourceManager.GetString("Men017Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the unused private set accessor from the {0} auto property..
        /// </summary>
        internal static string Men017MessageFormat {
            get {
                return ResourceManager.GetString("Men017MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unused private setter.
        /// </summary>
        internal static string Men017Title {
            get {
                return ResourceManager.GetString("Men017Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric literals should use digit separators to improve readability..
        /// </summary>
        internal static string Men018Description {
            get {
                return ResourceManager.GetString("Men018Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The numeric literal {0} should use digit separators..
        /// </summary>
        internal static string Men018MessageFormat {
            get {
                return ResourceManager.GetString("Men018MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use digit separators.
        /// </summary>
        internal static string Men018Title {
            get {
                return ResourceManager.GetString("Men018Title", resourceCulture);
            }
        }
    }
}
